# Generated by Django 3.2.23 on 2024-01-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20240108_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default='1999-04-23'),
            preserve_default=False,
        ),
    ]
